# Generated by Django 2.2.6 on 2019-12-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='collectible_specified_fields',
        ),
    ]
