# Generated by Django 2.2.6 on 2019-12-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191218_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='collectible_specified_fields',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
