# Generated by Django 2.2.6 on 2019-12-18 16:46

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_collectible_collectible_specified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='fields',
            field=djongo.models.fields.ListField(default=[]),
        ),
    ]
