# Generated by Django 2.2.6 on 2019-12-04 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191203_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('type', models.CharField(choices=[('T', 'TextField'), ('N', 'Number')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=main.models.MetaData, null=True)),
                ('basic_fields', djongo.models.fields.EmbeddedModelField(model_container=main.models.BasicFields, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category')),
                ('object_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.ObjectType')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='fields',
            field=models.ManyToManyField(to='main.Field'),
        ),
    ]
