# Generated by Django 2.2.6 on 2019-12-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191218_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('collectible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Collectible')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
            ],
            bases=('main.collectible',),
        ),
    ]
