# Generated by Django 2.2.6 on 2019-12-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_collectible_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='fields',
        ),
    ]
