# Generated by Django 3.0.2 on 2020-01-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='country',
            field=models.CharField(default='Poland', max_length=100, verbose_name='Event Country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(verbose_name='Event Year'),
        ),
    ]
