# Generated by Django 2.2.6 on 2019-12-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_collectible_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
