# Generated by Django 2.2.6 on 2019-12-18 11:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacingModel',
            fields=[
                ('collectible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.Collectible')),
                ('car_fields', djongo.models.fields.EmbeddedModelField(model_container=main.models.CarFields, null=True)),
                ('racing_fields', djongo.models.fields.EmbeddedModelField(model_container=main.models.CarFields, null=True)),
            ],
            bases=('main.collectible',),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
