# Generated by Django 2.2.6 on 2019-12-04 08:29

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191204_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('fields', djongo.models.fields.ArrayModelField(model_container=main.models.Field, model_form_class=main.models.FieldForm, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='object_type',
        ),
        migrations.AddField(
            model_name='category',
            name='extra_fields',
            field=djongo.models.fields.ArrayModelField(model_container=main.models.Field, model_form_class=main.models.FieldForm, null=True),
        ),
        migrations.AddField(
            model_name='collectible',
            name='collectible_related_fields',
            field=djongo.models.fields.ArrayModelField(model_container=main.models.Field, model_form_class=main.models.FieldForm, null=True),
        ),
        migrations.DeleteModel(
            name='ObjectType',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Type'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Type'),
        ),
    ]
