# Generated by Django 2.2.6 on 2019-12-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_field_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
