# Generated by Django 3.0.2 on 2020-01-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_auto_20200126_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='producer',
            field=models.CharField(max_length=40, verbose_name='Producer / Publishing House'),
        ),
    ]
