# Generated by Django 3.0.2 on 2020-01-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20200126_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Cena')),
                ('collectible',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_collection',
                                   to='main.Collectible')),
                ('profile',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_collection',
                                   to='main.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='collection',
            field=models.ManyToManyField(related_name='collection', through='main.PrivateCollection',
                                         to='main.Collectible'),
        ),
    ]
