# Generated by Django 2.2.6 on 2019-12-04 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191204_0935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
