# Generated by Django 3.0.2 on 2020-01-26 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_auto_20200126_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatecollection',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='collection',
        ),
        migrations.AddField(
            model_name='collectible',
            name='owners',
            field=models.ManyToManyField(related_name='collection', through='main.PrivateCollection',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privatecollection',
            name='bought_at',
            field=models.DateField(blank=True, null=True, verbose_name='Got at'),
        ),
        migrations.AddField(
            model_name='privatecollection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='profile_collection', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
