# Generated by Django 2.2.6 on 2019-12-04 08:58

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('C', 'CharField'), ('N', 'Number')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='extra_fields',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='collectible_related_fields',
        ),
        migrations.AlterField(
            model_name='collectible',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CollectibleType'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='collectibletype',
            name='fields',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Field'),
        ),
        migrations.AddField(
            model_name='category',
            name='fields',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Field'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='collectible_specified_fields',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Field'),
        ),
    ]
