# Generated by Django 3.0.2 on 2020-01-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_auto_20200126_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_base',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
