# Generated by Django 2.2.6 on 2019-12-04 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibletype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.CollectibleType'),
        ),
    ]
