# Generated by Django 3.0.2 on 2020-01-29 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_category_url_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='_customuser_watchers_+',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isRead', models.BooleanField()),
                ('collectible',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications',
                                   to='main.Collectible')),
                ('receiver',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications',
                                   to=settings.AUTH_USER_MODEL)),
                ('sender',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_send',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
