# Generated by Django 2.2.6 on 2019-12-04 10:02

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_collectibletype_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='fields',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Field'),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='collectible_specified_fields',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('B', 'Bool'), ('C', 'CharField'), ('I', 'Number')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='CollectibleType',
        ),
    ]
