# Generated by Django 3.0.2 on 2020-02-15 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0011_auto_20200215_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='categories',
        ),
        migrations.AddField(
            model_name='collectible',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category'),
        ),
    ]
