# Generated by Django 3.0.2 on 2020-02-15 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_auto_20200215_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url_base',
        ),
    ]
