# Generated by Django 3.0.2 on 2020-02-15 17:24

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0013_remove_category_url_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='main.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
    ]
