# Generated by Django 3.0.2 on 2020-02-15 20:02

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0014_auto_20200215_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             related_name='collectibles', to='main.Category'),
        ),
    ]
