# Generated by Django 3.0.2 on 2020-02-15 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0015_auto_20200215_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='collectibles', to='main.Category'),
        ),
    ]
