# Generated by Django 3.0.2 on 2020-02-15 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0017_auto_20200215_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='collectibles',
                                    to='main.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('R', 'Race'), ('W', 'Rally'), ('X', 'Rallycross'), ('A', 'War')],
                                   max_length=1, verbose_name='Type'),
        ),
    ]
