# Generated by Django 3.0.2 on 2020-02-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0018_auto_20200215_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='collectibles', to='main.Category'),
        ),
    ]
