# Generated by Django 3.0.2 on 2020-02-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200215_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='watchers',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_watchers_+', to='main.UserProfile'),
        ),
    ]
