# Generated by Django 3.0.2 on 2020-02-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200216_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(choices=[('S', 'Soft'), ('H', 'Hard')], max_length=1, verbose_name='Cover'),
        ),
    ]
