# Generated by Django 3.0.2 on 2020-02-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200219_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacingVehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='Brand')),
                ('model', models.CharField(max_length=30, verbose_name='Model')),
                ('car_year', models.IntegerField(verbose_name='Production Year')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('scale', models.IntegerField(verbose_name='Scale 1:')),
                ('body_style', models.CharField(choices=[('W', 'Wagon'), ('S', 'Sedan'), ('H', 'Hatchback'), ('C', 'Coupe'), ('T', 'Pickup truck'), ('U', 'SUV')], max_length=1, verbose_name='Body style')),
                ('engine_system', models.CharField(choices=[('I', 'Inline'), ('V', 'V'), ('W', 'W'), ('R', 'Rotary'), ('F', 'Flat')], max_length=1, verbose_name='Engine Type (System)')),
                ('engine_cylinders', models.IntegerField(verbose_name='Number of cylinders')),
                ('engine_capacity', models.FloatField(verbose_name='Capacity')),
                ('driver', models.CharField(max_length=60, verbose_name='Driver')),
                ('co_driver', models.CharField(blank=True, max_length=60, null=True, verbose_name='Co-driver')),
                ('engine_supplier', models.CharField(blank=True, max_length=60, null=True, verbose_name='Engine Supplier')),
                ('tire_supplier', models.CharField(blank=True, max_length=60, null=True, verbose_name='Tires Supplier')),
                ('car_number', models.IntegerField(blank=True, null=True, verbose_name='Car start number')),
                ('car_class', models.CharField(blank=True, max_length=30, null=True, verbose_name='Class')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Position')),
                ('series', models.CharField(blank=True, max_length=60, null=True, verbose_name='Series')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='StreetCarModel',
            new_name='VehicleModel',
        ),
        migrations.DeleteModel(
            name='RacingCarModel',
        ),
    ]
