# Generated by Django 3.0.2 on 2020-02-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200219_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='form',
            field=models.CharField(choices=[('BOOK_FORM', 'Książka'), ('WATCH_FORM', 'Zegarek'), ('VEHICLE_MODEL_FORM', 'Model samochodu'), ('RACING_VEHICLE_MODEL_FORM', 'Model samochodu wyścigowego')], default='BOOK_FORM', max_length=50),
        ),
    ]
