# Generated by Django 3.0.2 on 2020-02-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_category_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='isRead',
            new_name='is_read',
        ),
        migrations.AddField(
            model_name='racingvehiclemodel',
            name='wheels_number',
            field=models.IntegerField(default=4, verbose_name='Wheels number'),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='wheels_number',
            field=models.IntegerField(default=4, verbose_name='Wheels number'),
        ),
        migrations.AlterField(
            model_name='category',
            name='form',
            field=models.CharField(choices=[('BOOK_FORM', 'Książka'), ('WATCH_FORM', 'Zegarek'), ('VEHICLE_MODEL_FORM', 'Model pojazdu'), ('RACING_VEHICLE_MODEL_FORM', 'Model pojazdu wyścigowego')], default='BOOK_FORM', max_length=50),
        ),
    ]
