# Generated by Django 3.0.2 on 2020-02-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200222_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ADDED', 'was added to collection of'), ('ACCEPTED', 'Collectible added by you is accepted'), ('WATCHED', 'added you to his watcn list')], default='ADDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='collectible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='main.Collectible'),
        ),
    ]
