# Generated by Django 3.0.2 on 2020-02-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200224_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='watched',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='observed',
            field=models.ManyToManyField(blank=True, related_name='_userprofile_observed_+', to='main.UserProfile'),
        ),
    ]
