# Generated by Django 3.0.2 on 2020-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200224_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='racingvehiclemodel',
            name='engine_capacity',
            field=models.FloatField(verbose_name='Capacity (cm3)'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='engine_capacity',
            field=models.FloatField(verbose_name='Capacity (cm3)'),
        ),
    ]
