# Generated by Django 2.2.9 on 2020-01-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20200121_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
