# Generated by Django 2.2.9 on 2020-01-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_auto_20200122_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racingcarmodel',
            name='limited_production',
        ),
        migrations.RemoveField(
            model_name='streetcarmodel',
            name='limited_production',
        ),
        migrations.AddField(
            model_name='collectible',
            name='limited_production',
            field=models.IntegerField(blank=True, null=True, verbose_name='Limited production'),
        ),
    ]
