# Generated by Django 2.2.9 on 2020-01-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20200122_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='racingcarmodel',
            name='event_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Country'),
        ),
        migrations.AddField(
            model_name='racingcarmodel',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name'),
        ),
        migrations.AddField(
            model_name='racingcarmodel',
            name='event_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Event Year'),
        ),
    ]
