# Generated by Django 2.2.9 on 2020-01-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0005_auto_20200122_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('R', 'Race'), ('W', 'Rally'), ('X', 'Rallycross'), ('W', 'War')],
                                          max_length=1, verbose_name='Type')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Name')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Event Year')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Event Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='racingcarmodel',
            name='event_country',
        ),
        migrations.RemoveField(
            model_name='racingcarmodel',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='racingcarmodel',
            name='event_year',
        ),
    ]
