# Generated by Django 2.2.9 on 2020-01-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_auto_20200122_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racingcarmodel',
            name='event',
        ),
        migrations.AddField(
            model_name='racingcarmodel',
            name='eventx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Event'),
        ),
    ]
