# Generated by Django 2.2.9 on 2020-01-22 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_auto_20200122_0326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='racingcarmodel',
            old_name='eventx',
            new_name='event',
        ),
    ]
