# Generated by Django 2.2.9 on 2020-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_auto_20200122_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='producer',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Producer / Publishing House'),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='product_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Product Code / Model Number'),
        ),
        migrations.AlterField(
            model_name='racingcarmodel',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='racingcarmodel',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='streetcarmodel',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='streetcarmodel',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Model'),
        ),
    ]
