BOOK_FORM = 'BOOK_FORM'
WATCH_FORM = 'WATCH_FORM'
VEHICLE_MODEL_FORM = 'VEHICLE_MODEL_FORM'
RACING_VEHICLE_MODEL_FORM = 'RACING_VEHICLE_MODEL_FORM'

FORM_CHOICES = (
    (BOOK_FORM, 'Książka'),
    (WATCH_FORM, 'Zegarek'),
    (VEHICLE_MODEL_FORM, 'Model pojazdu'),
    (RACING_VEHICLE_MODEL_FORM, 'Model pojazdu wyścigowego'),
)